### ISSUE TITLE
선수 테이블의 포지션 unique

### ISSUE THREAD

**Issue by jy-b** [hyunsb/baseball-management-application#7]
@hyunsb 
포지션별로 유니크하게 잡으면 타 팀에도 같은 포지션이 존재 할 수 없음
position varchar(20) unique not null

다중 유니크 제약 필요
-> position varchar(20) not null
     unique key (position, team_id)

**Comment by hyunsb** [comment]
확인했습니다!

**Comment by hyunsb** [comment]
확인했습니다!
